/*
 * wallart-atlas.js: where each piece of the whoop room's wall art is in
 * assets/wallart/atlas.webp, and its printed size in true metres. GENERATED by
 * scripts/wallart.js from the slap pack: regenerate, do not edit.
 *
 * x, y, w, h are atlas pixels from the top left. printW and printH are
 * what the piece measures on a real wall; the room multiplies them by
 * MICRO_SCALE like every other length in it. rev is a hash of the image,
 * for its URL. Packed at 405 px per printed metre.
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

export const WALLART = {
  url: 'assets/wallart/atlas.webp',
  rev: 'cc911c84d03b',
  size: 2048,
  pieces: {
    bannerVisor: { x: 12, y: 1363, w: 1782, h: 327, printW: 4.4, printH: 0.807 },
    bannerWave: { x: 12, y: 1000, w: 1782, h: 351, printW: 4.4, printH: 0.866 },
    nobori: { x: 12, y: 12, w: 267, h: 588, printW: 0.66, printH: 1.452 },
    posterBubble: { x: 644, y: 12, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    posterChibi: { x: 291, y: 12, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    posterCity: { x: 997, y: 12, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    posterEma: { x: 997, y: 506, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    posterGoggles: { x: 644, y: 506, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    posterPilot: { x: 1350, y: 12, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    posterSea: { x: 291, y: 506, w: 341, h: 482, printW: 0.841, printH: 1.189 },
    wordmark: { x: 12, y: 1702, w: 1215, h: 325, printW: 3, printH: 0.804 },
  },
};
