/*
 * generate-sitemap.js: generate sitemap.xml including wiki article pages
 * that are allowed to be indexed.
 *
 * This file is part of the WebFPVSimulator landing page.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

/* Load articles and indexing config */
const { ARTICLES } = await import('../src/wiki/articles.js');
const { allCliPages } = await import('../src/wiki/cli.js');
const indexConfig = JSON.parse(readFileSync(join(root, 'wiki-index-config.json'), 'utf8'));

function shouldIndex(articleId) {
  if (indexConfig.globalIndexing) {
    return true;
  }
  return indexConfig.allowIndexing.includes(articleId);
}

const baseUrls = [
  { loc: 'https://webfpv.org/', changefreq: 'weekly', priority: '1.0' },
  { loc: 'https://webfpv.org/sim/', changefreq: 'weekly', priority: '0.9' },
  { loc: 'https://webfpv.org/wiki/', changefreq: 'monthly', priority: '0.8' },
  { loc: 'https://webfpv.org/notes/', changefreq: 'monthly', priority: '0.8' },
  { loc: 'https://webfpv.org/stickers/', changefreq: 'monthly', priority: '0.5' },
  { loc: 'https://webfpv.org/board/', changefreq: 'daily', priority: '0.7' },
  { loc: 'https://webfpv.org/sim/src/trackbuilder/index.html', changefreq: 'monthly', priority: '0.6' },
];

const wikiUrls = [];

/* Add indexed wiki articles */
for (const article of ARTICLES) {
  if (shouldIndex(article.id)) {
    wikiUrls.push({
      loc: `https://webfpv.org/wiki/${article.id}/`,
      changefreq: 'monthly',
      priority: '0.7',
    });
  }
}

/* Add indexed CLI pages */
const cliPages = allCliPages();
for (const page of cliPages) {
  if (shouldIndex(page.id)) {
    wikiUrls.push({
      loc: `https://webfpv.org/wiki/${page.id}/`,
      changefreq: 'monthly',
      priority: '0.6',
    });
  }
}

const allUrls = [...baseUrls, ...wikiUrls];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by scripts/generate-sitemap.js.
  
  The pages of webfpv.org: the landing page, the simulator, the board, and
  indexed wiki articles. Wiki articles are controlled by wiki-index-config.json:
  only articles with indexing enabled appear here.
  
  To regenerate: node scripts/generate-sitemap.js
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${allUrls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;

writeFileSync(join(root, 'sitemap.xml'), xml, 'utf8');
console.log(`Generated sitemap.xml with ${allUrls.length} URLs (${wikiUrls.length} wiki articles indexed)`);
