/*
 * page-lint.js: the things about a page that are true or false, not matters
 * of taste.
 *
 * WHY THIS EXISTS.
 *
 * A review found five defects here that no check could see, because none of
 * them is a wrong value in a data file. They are a heading behind a fixed
 * bar, a favicon whose path data closes to the wrong x, a share card that
 * exists on four pages and not on the fifth, thirty six articles sharing one
 * tab title, and a sitemap nobody wrote. Every one is checkable, and none of
 * them was checked.
 *
 * WHAT IT DOES NOT DO. It does not open a browser, so it cannot tell you the
 * page looks right. `npm run serve` and a pair of eyes is still the answer to
 * that, as CLAUDE.md says. What this holds is the part that stays true
 * whatever the browser does.
 *
 * This file is part of the WebFPVSimulator landing page.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { readFile, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const rows = [];
let failed = 0;

function check(name, ok, detail) {
  rows.push([name, ok ? 'ok' : 'FAIL', detail]);
  if (!ok) {
    failed += 1;
  }
}

async function exists(rel) {
  try {
    await access(join(root, rel));
    return true;
  } catch (e) {
    return false;
  }
}

const index = await readFile(join(root, 'index.html'), 'utf8');
const wiki = await readFile(join(root, 'wiki/index.html'), 'utf8');
const wikiJs = await readFile(join(root, 'src/wiki/wiki.js'), 'utf8');
const mainJs = await readFile(join(root, 'src/main.js'), 'utf8');

/*
 * 1. ONE h1 A PAGE.
 *
 * Two h1 elements leave a document with no single heading a crawler or a
 * screen reader can name it by, and this page had the wordmark and the
 * closing shout both claiming it.
 */
{
  const n = (index.match(/<h1[\s>]/g) || []).length;
  check('index.html: exactly one h1', n === 1, `${n} in the markup`);
  /* The wiki's heading is the open article's title, so it is built rather
   * than written. The static markup must therefore have none, and wiki.js
   * must build exactly one. The page used to have neither: the article
   * opened at h2 with nothing above it. */
  const staticH1 = (wiki.match(/<h1[\s>]/g) || []).length;
  const builtH1 = (wikiJs.match(/el\('h1'/g) || []).length;
  check(
    'wiki/index.html: exactly one h1, built from the article title',
    staticH1 === 0 && builtH1 === 1,
    `${staticH1} in the markup, ${builtH1} built in wiki.js`,
  );
}

/*
 * 2. THE CLOSE RESERVES THE FIXED BAR'S HEIGHT.
 *
 * #close is min-height 100vh and centres its content, and a centred column
 * taller than its box overflows both ways. At the bottom of the page there
 * is no scroll left to recover the top with, so the film's last words were
 * drawn behind the nav: measured at 1440x900, headline top 24, nav bottom 66.
 * The padding has to be at least the bar, and the centring has to be safe.
 */
{
  const hasVar = /--nav-h:\s*\d+px/.test(index);
  const padded = /padding:\s*max\(clamp\([^)]*\),\s*calc\(var\(--nav-h\)/.test(index);
  const safe = /justify-content:\s*safe center/.test(index);
  check(
    'index.html: the close clears the fixed nav',
    hasVar && padded && safe,
    `--nav-h ${hasVar ? 'set' : 'MISSING'}, padding ${padded ? 'reserves it' : 'DOES NOT'}, centring ${safe ? 'safe' : 'unsafe, so overflow goes upward'}`,
  );
}

/*
 * 3. THE FIRST FRAME CARRIES THE HEADLINE.
 *
 * Act 1's copy opened at T > 0.04, about a screen of scroll, so the page as
 * it loaded was a dark stage and the word SCROLL. The page's whole claim was
 * off screen until scrollY passed a thousand pixels.
 */
{
  const gated = /setCopy\('assemble',\s*T\s*>\s*0/.test(mainJs);
  check(
    'src/main.js: act 1 copy is on screen at T = 0',
    !gated,
    gated ? 'the copy is still gated behind a scroll' : 'visible from the first frame',
  );
}

/*
 * 4. THE ICONS ARE THE FAMILY'S, NOT A DRAWING OF ONE.
 *
 * CLAUDE.md: the site icon is generated by the simulator's scripts/icons.js.
 * The wiki inlined a hand written data URI of four squares, and the fourth
 * path read M18 18h5v5H9z, closing back to x=9, so it drew a wedge fused to
 * its neighbour. A generated file cannot be wrong in that way.
 */
for (const [name, src] of [['index.html', index], ['wiki/index.html', wiki]]) {
  const inlined = /rel="icon"[^>]*href="data:/.test(src);
  check(`${name}: icon is a file, not an inline drawing`, !inlined, inlined ? 'a data URI icon is hand drawn and can be, and was, malformed' : 'points at the generated icon');
}

/*
 * 5. EVERY PAGE RENDERS A CARD WHEN IT IS PASTED SOMEWHERE.
 */
for (const [name, src] of [['index.html', index], ['wiki/index.html', wiki]]) {
  const need = ['rel="canonical"', 'og:title', 'og:description', 'og:image', 'twitter:card', 'name="description"'];
  const missing = need.filter((t) => !src.includes(t));
  check(`${name}: has a share card`, missing.length === 0, missing.length ? `missing ${missing.join(', ')}` : 'canonical, og and twitter all present');
}

/*
 * 6. EVERY ARTICLE IS ITS OWN ENTRY IN THE TAB STRIP AND THE BACK LIST.
 */
{
  const sets = wikiJs.includes('setDocumentTitle') && /document\.title\s*=\s*`\$\{page\.title\}/.test(wikiJs);
  const called = /this\.setDocumentTitle\(page\)/.test(wikiJs);
  check(
    'src/wiki/wiki.js: an article sets the document title',
    sets && called,
    sets && called ? 'title follows the open article' : 'all thirty six articles share one title',
  );
}

/*
 * 7. THE SITE IS DISCOVERABLE AT ALL.
 *
 * The Worker serves this repository at the root, so these two files govern
 * all five pages. Production's robots.txt was Cloudflare's injected stub with
 * no Sitemap line, and /sitemap.xml was a 404.
 */
{
  const hasRobots = await exists('robots.txt');
  const hasMap = await exists('sitemap.xml');
  check('robots.txt exists', hasRobots, hasRobots ? 'at the site root' : 'MISSING, so production serves Cloudflare\'s stub');
  check('sitemap.xml exists', hasMap, hasMap ? 'at the site root' : 'MISSING');
  if (hasRobots && hasMap) {
    const robots = await readFile(join(root, 'robots.txt'), 'utf8');
    const map = await readFile(join(root, 'sitemap.xml'), 'utf8');
    check('robots.txt names the sitemap', /^Sitemap:\s*https:\/\/\S+sitemap\.xml/m.test(robots), 'the line a crawler reads');
    /* Every page the family has, and no page it does not. A sitemap that
     * lists a 404 is worse than no sitemap. */
    const want = ['https://webfpv.org/', 'https://webfpv.org/sim/', 'https://webfpv.org/wiki/', 'https://webfpv.org/board/'];
    const missing = want.filter((u) => !map.includes(`<loc>${u}</loc>`));
    check('sitemap lists every page of the family', missing.length === 0, missing.length ? `missing ${missing.join(', ')}` : `${want.length} pages plus the builder`);
    check('sitemap is well formed', /<\?xml/.test(map) && /sitemaps\.org\/schemas\/sitemap\/0\.9/.test(map), 'declaration and the real namespace URL');
  }
}

/*
 * 8. THE ORIGINS ARE STILL THE ONES config.js OWNS.
 *
 * CLAUDE.md: if a mount point moves, src/config.js is the file that changes.
 * A hard coded onrender.com address anywhere else is the failure mode that
 * rule exists to prevent, and it is invisible until someone renames a
 * service.
 */
{
  const files = { 'index.html': index, 'wiki/index.html': wiki, 'src/main.js': mainJs };
  const bad = [];
  for (const [name, src] of Object.entries(files)) {
    if (/onrender\.com/.test(src)) {
      bad.push(name);
    }
  }
  check('no service hostname outside config.js', bad.length === 0, bad.length ? `${bad.join(', ')} name a Render host directly` : 'every origin comes from src/config.js');
}

/*
 * 9. NO EM DASH OR EN DASH ANYWHERE.
 *
 * CLAUDE.md is explicit, and the page's own separator is a middle dot. This
 * is the cheapest check in the file and it catches a real habit.
 */
{
  const bad = [];
  for (const [name, src] of [['index.html', index], ['wiki/index.html', wiki], ['src/main.js', mainJs], ['src/wiki/wiki.js', wikiJs]]) {
    if (/[\u2013\u2014]/.test(src)) {
      bad.push(name);
    }
  }
  check('no en or em dashes', bad.length === 0, bad.length ? bad.join(', ') : 'the separator is &#183; as the house style says');
}

const w = Math.max(...rows.map((r) => r[0].length));
console.log('page-lint: the parts of the pages that are true or false\n');
for (const [name, status, detail] of rows) {
  console.log(`${status === 'ok' ? ' ok ' : 'FAIL'}  ${name.padEnd(w)}  ${detail}`);
}
console.log(`\n${rows.length - failed} of ${rows.length} checks clean`);
process.exit(failed === 0 ? 0 : 1);
