/*
 * velocity.js: measure how the code has grown from the git history of the
 * three repositories, and draw it at the top of the patch notes.
 *
 * WHY THIS EXISTS. The patch notes say what changed. This says how fast, and
 * it is measured, not remembered: lines of source at the end of every day,
 * and commits every day, for the simulator, the board and this site. A graph
 * somebody types in goes stale the day after, so this one is a function of
 * the history, and `npm run lint:page` fails when the page stops agreeing
 * with it.
 *
 * HOW TO RUN IT, whenever a patch notes entry is added.
 *
 *   git fetch origin main                  in each of the three repositories
 *   node scripts/velocity.js ../WebFPVSimulator ../WebFPVSimulator-LeaderBoard
 *
 * The first path is the simulator, the second is the board, and this
 * repository is the third. It reads each one's origin/main (main if there is
 * no origin, HEAD if there is no main), writes notes/velocity.json and
 * rewrites the block between the two marker comments in notes/index.html.
 * Regenerate, do not edit either. `node scripts/velocity.js --check` asks
 * only whether the page still says what the JSON says, and reads no git.
 *
 * WHAT "CODE" IS. Hand written .js, .mjs, .c, .h, .html and .css files, and
 * nothing else. Not counted, and listed in the JSON so it can be audited:
 * code that is somebody else's (the vendored town), files a script writes,
 * copies of the simulator's files in the other two repositories, records,
 * pictures, and this page, which would otherwise count its own graph. The
 * measure is the point: 59,000 lines of PROGRESS.md and 91,000 lines of
 * generated wiki pages would each have made the code look four times as big.
 *
 * HOW IT IS MEASURED. Each repository's first parent chain is walked, and
 * every step's diff against its first parent is summed by day. That is exact:
 * the sum equals a direct count of the files at the head, and this script
 * checks that and stops if they differ. Adding up every non merge commit
 * instead drifts by dozens of lines, because a merge that was fixed by hand
 * carries edits no other commit has. A shallow clone is refused, because a
 * truncated history is a wrong graph that looks like a right one. Days are
 * Perth time, the owner's calendar and the one the patch notes are cut by.
 * A line's day is its commit's author date. Commits are the non merge
 * commits reachable from the same ref, by author date.
 *
 * WHAT THE COLOURS ARE. The stack is the simulator (mint), the board (amber)
 * and this site (sakura): the site's own words for something good, an
 * instrument, and chrome. They are the dataviz palette's dark steps for the
 * aqua, yellow and magenta families, validated against the page's surface.
 * Mint and sakura must never touch: to a viewer with deuteranopia they are
 * the same colour (CVD delta E 1.6 against a floor of 6), so amber sits
 * between them and the stack order is fixed. The page's CSS holds the hexes.
 *
 * HOW IT IS DRAWN. Two panels share one row of days: lines of source, stacked
 * and cumulative, and commits a day, stacked. The marks are SVG in a viewBox
 * that scales as a picture. Every word is HTML at a fixed size, placed by
 * percentages of the plot, because text inside an SVG shrinks with it and at
 * 430 px was seven pixels tall. A table of every number sits under the graph,
 * and notes/velocity.js reads its hover from that table, so nothing is shown
 * that the table does not say. Nothing here reads the clock: the same history
 * draws the same bytes, which is what lets the lint compare the page with the
 * JSON.
 *
 * This file is part of the WebFPVSimulator landing page.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

export const DATA = 'notes/velocity.json';
export const PAGE = 'notes/index.html';
export const BEGIN = '<!-- velocity:begin generated by scripts/velocity.js, regenerate and do not edit -->';
export const END = '<!-- velocity:end -->';

export const UTC_OFFSET_HOURS = 8;
export const EXTENSIONS = ['js', 'mjs', 'c', 'h', 'html', 'css'];

/* The order is the stack, bottom to top, and it is fixed: see the header. */
export const REPOS = [
  {
    id: 'sim',
    name: 'Simulator',
    end: 'Simulator',
    skip: [
      ['**/vendored/**', 'the town, vendored from another project'],
      ['src/fc/catalog-data.js', 'generated from the flight controller settings'],
      ['src/trackbuilder/presets.js', 'generated track presets'],
      ['src/fresh.js', 'generated module list'],
      ['src/art/wallart-atlas.js', 'generated'],
      ['.loop', 'the improvement loops\' records'],
      ['.claude', 'agent settings'],
      ['vendor', 'Betaflight, a submodule'],
      ['dist', 'build output'],
      ['assets', 'pictures and sound'],
      ['tests/goldens', 'recorded traces'],
      ['tests/fixtures', 'recorded inputs'],
    ],
  },
  {
    id: 'board',
    name: 'Board',
    end: 'Board',
    skip: [
      ['public/sim', 'copied from the simulator'],
      ['data', 'stored data'],
      ['node_modules', 'installed packages'],
    ],
  },
  {
    id: 'site',
    name: 'This site',
    end: 'Site',
    skip: [
      ['**/vendored/**', 'the town, vendored from another project'],
      ['src/sim', 'copied from the simulator'],
      ['src/fc', 'copied from the simulator'],
      ['src/yard-data.js', 'generated'],
      ['src/room-data.js', 'generated'],
      ['src/stickers-data.js', 'generated'],
      ['notes/index.html', 'the patch notes, which carry this graph'],
      ['stickers/index.html', 'the sticker pack, art'],
      ['wiki/*/index.html', 'the wiki articles, one generated page each'],
      ['node_modules', 'installed packages'],
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Measuring                                                            */
/* ------------------------------------------------------------------ */

function git(cwd, args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8', maxBuffer: 1 << 30 });
}

function refOf(cwd) {
  for (const ref of ['origin/main', 'main', 'HEAD']) {
    try {
      git(cwd, ['rev-parse', '--verify', '-q', `${ref}^{commit}`]);
      return ref;
    } catch (e) {
      /* Not there. Try the next. */
    }
  }
  throw new Error(`${cwd}: no origin/main, main or HEAD`);
}

function pathspec(repo) {
  const skip = repo.skip.map(([p]) => `:(exclude${p.includes('*') ? ',glob' : ''})${p}`);
  return [...EXTENSIONS.map((e) => `*.${e}`), ...skip];
}

export function dayOf(unixSeconds) {
  return new Date((unixSeconds + UTC_OFFSET_HOURS * 3600) * 1000).toISOString().slice(0, 10);
}

function directCount(cwd, ref, spec) {
  let out = '';
  try {
    out = git(cwd, ['grep', '-I', '-c', '', ref, '--', ...spec]);
  } catch (e) {
    return 0; /* git grep exits 1 when nothing matches. */
  }
  let n = 0;
  for (const line of out.split('\n')) {
    if (line) {
      n += Number(line.slice(line.lastIndexOf(':') + 1));
    }
  }
  return n;
}

function measure(repo, cwd) {
  if (git(cwd, ['rev-parse', '--is-shallow-repository']).trim() === 'true') {
    throw new Error(`${cwd} is a shallow clone. Fetch its whole history first: git fetch --unshallow`);
  }
  const ref = refOf(cwd);
  const spec = pathspec(repo);

  const net = new Map();
  let day = null;
  const stat = git(cwd, ['log', ref, '--first-parent', '-m', '--no-renames', '--numstat', '--format=@%at', '--', ...spec]);
  for (const line of stat.split('\n')) {
    if (line.startsWith('@')) {
      day = dayOf(Number(line.slice(1)));
      continue;
    }
    const m = /^(\d+|-)\t(\d+|-)\t/.exec(line);
    if (m && day) {
      const add = m[1] === '-' ? 0 : Number(m[1]);
      const del = m[2] === '-' ? 0 : Number(m[2]);
      net.set(day, (net.get(day) || 0) + add - del);
    }
  }

  const commits = new Map();
  for (const t of git(cwd, ['log', ref, '--no-merges', '--format=%at']).split('\n')) {
    if (t) {
      const d = dayOf(Number(t));
      commits.set(d, (commits.get(d) || 0) + 1);
    }
  }

  const summed = [...net.values()].reduce((s, v) => s + v, 0);
  const direct = directCount(cwd, ref, spec);
  if (summed !== direct) {
    throw new Error(`${repo.id}: the history sums to ${summed} lines but the files at ${ref} hold ${direct}`);
  }
  return { net, commits, head: git(cwd, ['rev-parse', '--short=8', ref]).trim(), ref, total: direct };
}

function daysBetween(first, last) {
  const out = [];
  for (let t = Date.parse(`${first}T00:00:00Z`); t <= Date.parse(`${last}T00:00:00Z`); t += 86400000) {
    out.push(new Date(t).toISOString().slice(0, 10));
  }
  return out;
}

export function collect(paths) {
  const got = REPOS.map((r) => ({ repo: r, ...measure(r, paths[r.id]) }));
  const seen = got.flatMap((g) => [...g.net.keys(), ...g.commits.keys()]).sort();
  const days = daysBetween(seen[0], seen[seen.length - 1]);
  const lines = {};
  const commits = {};
  const heads = {};
  for (const g of got) {
    let run = 0;
    lines[g.repo.id] = days.map((d) => (run += g.net.get(d) || 0));
    commits[g.repo.id] = days.map((d) => g.commits.get(d) || 0);
    heads[g.repo.id] = g.head;
  }
  return {
    generated: 'scripts/velocity.js',
    heads,
    zone: `Perth, UTC+${UTC_OFFSET_HOURS}`,
    counted: EXTENSIONS,
    repos: REPOS.map((r) => ({ id: r.id, name: r.name, notCounted: r.skip.map(([path, why]) => ({ path, why })) })),
    first: days[0],
    days: days.length,
    lines,
    commits,
  };
}

/* One line per array, so a diff of the data reads as a diff of numbers. */
export function stringify(data) {
  const arr = (a) => `[${a.join(', ')}]`;
  const group = (o) => `{\n${Object.entries(o).map(([k, v]) => `    ${JSON.stringify(k)}: ${arr(v)}`).join(',\n')}\n  }`;
  const rest = { ...data };
  delete rest.lines;
  delete rest.commits;
  delete rest.repos;
  const head = Object.entries(rest).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`);
  const repos = `[\n${data.repos.map((r) => `    ${JSON.stringify(r)}`).join(',\n')}\n  ]`;
  return `{\n${head.join(',\n')},\n  "repos": ${repos},\n  "lines": ${group(data.lines)},\n  "commits": ${group(data.commits)}\n}\n`;
}

/* ------------------------------------------------------------------ */
/* Drawing                                                              */
/* ------------------------------------------------------------------ */

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const LONG = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const fmt = (n) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const f = (n) => n.toFixed(1);
const short = (iso) => `${Number(iso.slice(8))} ${MONTHS[Number(iso.slice(5, 7)) - 1]}`;
const long = (iso) => `${Number(iso.slice(8))} ${LONG[Number(iso.slice(5, 7)) - 1]}`;
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/*
 * The plot is drawn in a viewBox of exactly these units and scaled uniformly,
 * so a circle stays a circle and a rounded bar keeps its corner at any width.
 * Every word on the graph is HTML at a fixed size, placed by percentages of
 * the plot: a phone gets text it can read, not a shrunken copy of the
 * desktop's. The margins for those words are the page's CSS, not geometry.
 */
export const geometry = { pw: 420, aH: 190, bH: 110, gap: 2 };

function niceScale(max, want) {
  const raw = Math.max(max, 1) / want;
  const mag = 10 ** Math.floor(Math.log10(raw));
  const step = [1, 2, 2.5, 5, 10].map((m) => m * mag).find((s) => s >= raw);
  return { step, top: Math.ceil(Math.max(max, 1) / step) * step };
}

export function lastDay(data) {
  return new Date(Date.parse(`${data.first}T00:00:00Z`) + (data.days - 1) * 86400000).toISOString().slice(0, 10);
}

/* Which days get a date under the bars: every seventh counting back from the
   newest while the span is short, then the first of each month, thinned to
   about eight. Oldest first. */
function tickDays(days) {
  const n = days.length;
  if (n <= 70) {
    const out = [];
    for (let i = n - 1; i >= 0; i -= 7) {
      out.push(i);
    }
    return out.reverse();
  }
  const firsts = days.flatMap((d, i) => (d.endsWith('-01') ? [i] : []));
  const every = Math.max(1, Math.ceil(firsts.length / 8));
  return firsts.filter((_, k) => k % every === 0);
}

export function render(data) {
  const { pw, aH, bH, gap } = geometry;
  const ids = REPOS.map((r) => r.id);
  const names = Object.fromEntries(REPOS.map((r) => [r.id, r.name]));
  const ends = Object.fromEntries(REPOS.map((r) => [r.id, r.end]));
  const n = data.days;
  const days = daysBetween(data.first, lastDay(data));
  const slot = pw / n;
  const xAt = (i) => (i + 0.5) * slot;
  const pctX = (x) => `${f((x / pw) * 100)}%`;
  const lastI = n - 1;
  const multiYear = days[0].slice(0, 4) !== days[lastI].slice(0, 4);
  const dayLabel = (iso) => (multiYear ? `${short(iso)} ${iso.slice(0, 4)}` : short(iso));

  const total = days.map((_, i) => ids.reduce((s, id) => s + data.lines[id][i], 0));
  const perDay = days.map((_, i) => ids.reduce((s, id) => s + data.commits[id][i], 0));
  const commitsAll = perDay.reduce((s, v) => s + v, 0);
  const peakI = perDay.indexOf(Math.max(...perDay));

  /* ---- panel A: lines, stacked, cumulative ---- */
  const sa = niceScale(Math.max(...total), 3);
  const yA = (v) => aH * (1 - v / sa.top);
  const pctA = (y) => `${f((y / aH) * 100)}%`;
  const X = [0, ...days.map((_, i) => xAt(i))];
  const stack = [X.map(() => 0)];
  for (const id of ids) {
    const prev = stack[stack.length - 1];
    stack.push([0, ...data.lines[id]].map((v, j) => prev[j] + v));
  }
  let a = '';
  let aTicks = '';
  for (let t = 0; t <= sa.top; t += sa.step) {
    a += `<line class="${t === 0 ? 'ax' : 'g'}" x1="0" x2="${pw}" y1="${f(yA(t))}" y2="${f(yA(t))}"/>`;
    aTicks += `<span class="yt" style="top:${pctA(yA(t))}">${fmt(t)}</span>`;
  }
  ids.forEach((id, k) => {
    const top = X.map((x, j) => [x, yA(stack[k + 1][j])]);
    const bot = X.map((x, j) => [x, k === 0 ? yA(0) : yA(stack[k][j]) - gap]);
    const clamped = top.map(([x, y], j) => [x, Math.min(y, bot[j][1])]);
    const pts = (p) => p.map(([x, y]) => `${f(x)} ${f(y)}`).join('L');
    a += `<path class="fa s-${id}" d="M${pts(clamped)}L${pts([...bot].reverse())}Z"/>`;
  });
  for (let k = ids.length - 1; k >= 0; k -= 1) {
    a += `<path class="la s-${ids[k]}" d="M${X.map((x, j) => `${f(x)} ${f(yA(stack[k + 1][j]))}`).join('L')}"/>`;
  }
  /* The end labels ride the layers, and a label that would sit on another is dropped: the key and the tooltip carry it. */
  let labels = '';
  let lastY = Infinity;
  for (let k = 0; k < ids.length; k += 1) {
    const mid = (yA(stack[k + 1][n]) + yA(stack[k][n])) / 2;
    if (lastY === Infinity || lastY - mid >= 14) {
      labels += `<span class="lb s-${ids[k]}" style="top:${pctA(mid)}"><i class="k"></i>${esc(ends[ids[k]])}</span>`;
      lastY = mid;
    }
  }
  const topY = yA(total[lastI]);
  const end = `<span class="mk" style="left:${pctX(X[n])};top:${pctA(topY)}"></span><span class="val" style="top:${pctA(topY)}">${fmt(total[lastI])} lines</span>`;

  /* ---- panel B: commits a day, stacked bars ---- */
  const sb = niceScale(Math.max(...perDay), 4);
  const yB = (v) => bH * (1 - v / sb.top);
  const pctB = (y) => `${f((y / bH) * 100)}%`;
  const bw = Math.min(24, Math.max(slot * 0.72, slot - 2));
  let bars = '';
  let bTicks = '';
  for (let t = 0; t <= sb.top; t += sb.step) {
    bars += `<line class="${t === 0 ? 'ax' : 'g'}" x1="0" x2="${pw}" y1="${f(yB(t))}" y2="${f(yB(t))}"/>`;
    bTicks += `<span class="yt" style="top:${pctB(yB(t))}">${fmt(t)}</span>`;
  }
  const per = bH / sb.top;
  days.forEach((_, i) => {
    const segs = ids.map((id) => ({ id, v: data.commits[id][i] })).filter((s) => s.v > 0);
    let y = yB(0);
    segs.forEach((s, k) => {
      const h = Math.max(s.v * per, 1.5);
      const top = k === segs.length - 1;
      const drawn = top || h <= gap + 1 ? h : h - gap;
      const x0 = xAt(i) - bw / 2;
      const x1 = x0 + bw;
      const y0 = y;
      const y1 = y - drawn;
      if (top) {
        const r = Math.min(4, bw / 2, drawn);
        bars += `<path class="bar s-${s.id}" d="M${f(x0)} ${f(y0)}V${f(y1 + r)}Q${f(x0)} ${f(y1)} ${f(x0 + r)} ${f(y1)}H${f(x1 - r)}Q${f(x1)} ${f(y1)} ${f(x1)} ${f(y1 + r)}V${f(y0)}Z"/>`;
      } else {
        bars += `<rect class="bar s-${s.id}" x="${f(x0)}" y="${f(y1)}" width="${f(bw)}" height="${f(drawn)}"/>`;
      }
      y -= h;
    });
  });
  /* The peak's label is centred on its bar, unless the bar is near an end, where it hangs inward so it never leaves the plot. */
  const side = xAt(peakI) > pw * 0.7 ? 'r' : xAt(peakI) < pw * 0.3 ? 'l' : '';
  const peakX = xAt(peakI) + (side === 'r' ? bw / 2 : side === 'l' ? -bw / 2 : 0);
  const peak = `<span class="pk${side ? ` ${side}` : ''}" style="left:${pctX(peakX)};top:${pctB(yB(perDay[peakI]))}">${perDay[peakI]} on ${short(days[peakI])}</span>`;
  const marks = tickDays(days);
  let xs = '';
  marks.forEach((i, k) => {
    const alt = (marks.length - 1 - k) % 2 ? ' alt' : '';
    bars += `<line class="tick" x1="${f(xAt(i))}" x2="${f(xAt(i))}" y1="${bH}" y2="${bH + 5}"/>`;
    const withYear = multiYear || n > 70 ? days[i].slice(5, 7) === '01' : false;
    xs += `<span class="xt${alt}" style="left:${pctX(xAt(i))}">${withYear ? `${short(days[i])} ${days[i].slice(0, 4)}` : short(days[i])}</span>`;
  });

  /* ---- the key, the table, the words ---- */
  const key = ids.map((id) => `<li><span class="sw s-${id}"></span>${esc(names[id])} <span class="num">${fmt(data.lines[id][lastI])}</span></li>`).join('');
  const rows = [];
  for (let i = lastI; i >= 0; i -= 1) {
    const cells = [...ids.map((id) => data.lines[id][i]), total[i], ...ids.map((id) => data.commits[id][i]), perDay[i]];
    rows.push(`<tr><th scope="row">${dayLabel(days[i])}</th>${cells.map((v) => `<td>${fmt(v)}</td>`).join('')}</tr>`);
  }
  const summary = `Lines of source grew from ${fmt(total[0])} on ${long(days[0])} to ${fmt(total[lastI])} on ${long(days[lastI])}: ${ids.map((id) => `${names[id].toLowerCase()} ${fmt(data.lines[id][lastI])}`).join(', ')}.`;
  const busiest = `Commits a day, most on ${long(days[peakI])} with ${perDay[peakI]}. The table view has every day.`;
  const year = days[lastI].slice(0, 4);

  return [
    '<section id="velocity">',
    '  <h2>Velocity</h2>',
    `  <p class="when">${long(days[0])} to ${long(days[lastI])} ${year}</p>`,
    `  <p class="lede">${fmt(total[lastI])} lines of source after ${n} days, from ${fmt(commitsAll)} commits across the simulator, the board and this site.</p>`,
    '  <figure class="viz">',
    `    <ul class="key">${key}</ul>`,
    `    <div class="plots" tabindex="0" role="group" aria-label="Velocity graph. Use the left and right arrow keys to read one day at a time." data-n="${n}" data-ids="${ids.join(',')}">`,
    `      <div class="panel a" role="img" aria-label="${esc(summary)}">`,
    '        <p class="viz-h">Lines of source, at the end of each day</p>',
    '        <div class="frame">',
    `          <div class="plot" style="aspect-ratio:${pw}/${aH}">`,
    `            <svg viewBox="0 0 ${pw} ${aH}" focusable="false">${a}</svg>`,
    `            ${aTicks}${labels}${end}`,
    '          </div>',
    '        </div>',
    '      </div>',
    `      <div class="panel b" role="img" aria-label="${esc(busiest)}">`,
    '        <p class="viz-h">Commits a day</p>',
    '        <div class="frame">',
    `          <div class="plot" style="aspect-ratio:${pw}/${bH}">`,
    `            <svg viewBox="0 0 ${pw} ${bH}" focusable="false">`,
    '              <defs>',
    ...ids.map((id, k) => `                <pattern id="vel-p-${id}" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(${k === 1 ? 135 : 45})"><path d="M0 0V6" stroke="CanvasText" stroke-width="1.6"/>${k === 2 ? '<path d="M0 0H6" stroke="CanvasText" stroke-width="1.6"/>' : ''}</pattern>`),
    '              </defs>',
    `              ${bars}`,
    '            </svg>',
    `            ${bTicks}${peak}${xs}`,
    '          </div>',
    '        </div>',
    '      </div>',
    '      <div class="cross" hidden></div>',
    '      <div class="tip" hidden></div>',
    '      <p class="sr" aria-live="polite"></p>',
    '    </div>',
    `    <figcaption>Lines of source are the hand written .js, .mjs, .c, .h, .html and .css files on each repository's main branch, added up from its git history. Not counted: code that is not ours, files a script writes, the simulator's files copied into the board and this site, the wiki's generated pages, and this page. Commits are non merge commits by author date. Days are Perth time.</figcaption>`,
    '    <details class="viz-table">',
    '      <summary>Table view</summary>',
    '      <div class="scroll" tabindex="0">',
    '        <table>',
    '          <caption>Lines of source at the end of each day, and commits made that day, newest first.</caption>',
    '          <thead><tr><th rowspan="2" scope="col">Day</th><th colspan="4" scope="colgroup">Lines of source</th><th colspan="4" scope="colgroup">Commits</th></tr>',
    `          <tr>${ids.map((id) => `<th scope="col">${esc(names[id])}</th>`).join('')}<th scope="col">All</th>${ids.map((id) => `<th scope="col">${esc(names[id])}</th>`).join('')}<th scope="col">All</th></tr></thead>`,
    `          <tbody>${rows.join('')}</tbody>`,
    '        </table>',
    '      </div>',
    '    </details>',
    '  </figure>',
    '</section>',
  ].join('\n');
}

/* What sits in the page, markers included, indented as the page's sections are. */
export function block(data) {
  const body = render(data).split('\n').map((l) => (l ? `      ${l}` : l)).join('\n');
  return `      ${BEGIN}\n${body}\n      ${END}`;
}

export function splice(page, data) {
  const fresh = block(data);
  const at = page.indexOf(`      ${BEGIN}`);
  if (at !== -1) {
    const end = page.indexOf(END, at);
    if (end === -1) {
      throw new Error('the velocity begin marker has no end marker');
    }
    return page.slice(0, at) + fresh + page.slice(end + END.length);
  }
  /* A page with no graph yet gets it directly under the jump list, above the first entry. */
  const nav = page.indexOf('<nav class="weeks"');
  const close = nav === -1 ? -1 : page.indexOf('</nav>', nav);
  if (close === -1) {
    throw new Error('no jump list (nav.weeks) to put the graph under');
  }
  const after = close + '</nav>'.length;
  return `${page.slice(0, after)}\n\n${fresh}${page.slice(after)}`;
}

/* ------------------------------------------------------------------ */
/* Running                                                              */
/* ------------------------------------------------------------------ */

async function main() {
  const args = process.argv.slice(2);
  if (args[0] === '--check') {
    const data = JSON.parse(await readFile(join(root, DATA), 'utf8'));
    const page = await readFile(join(root, PAGE), 'utf8');
    const ok = page.includes(block(data)) && page.split(BEGIN).length === 2;
    console.log(ok ? 'the page says what notes/velocity.json says' : 'the page and notes/velocity.json disagree: run scripts/velocity.js');
    process.exit(ok ? 0 : 1);
  }
  if (args.length !== 2) {
    console.error('usage: node scripts/velocity.js <simulator checkout> <board checkout>\n       node scripts/velocity.js --check');
    process.exit(2);
  }
  const data = collect({ sim: resolve(args[0]), board: resolve(args[1]), site: root });
  await writeFile(join(root, DATA), stringify(data));
  const page = await readFile(join(root, PAGE), 'utf8');
  await writeFile(join(root, PAGE), splice(page, data));
  const last = data.days - 1;
  for (const id of REPOS.map((r) => r.id)) {
    console.log(`${id.padEnd(6)} ${String(data.lines[id][last]).padStart(8)} lines  ${String(data.commits[id].reduce((s, v) => s + v, 0)).padStart(5)} commits  at ${data.heads[id]}`);
  }
  console.log(`${data.first} to ${lastDay(data)}, ${data.days} days, written to ${DATA} and ${PAGE}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await main();
}
